spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost/jpa_1'
<<<<<<< HEAD
    username: root
    password:
  sql:
    init:
      mode: always
=======

    username: root
    password:

>>>>>>> 52ce524 (.)

  jpa:
    hibernate:
        ddl-auto: create        # DB 초기화 전략 (none, create, create-drop, update, validate)

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true

    defer-datasource-initialization: true
    database: mysql

  security:
    oauth2:
      client:
        registration:

          kakao:
            client-id: 0079af8e66a2f897721d5419a0933b70
            client-secret: zswRxlhG4BxDtwdibpuOIRyw6b75yekK
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  config:
    import: classpath:/application-secret.yml



jwt:
  issuer: yoonsu0325@gmail.com
  secret_key: studySpringbootttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh

